---
title: "gap_products_synopsis"
author: "Matt Callahan"
format: html
editor: visual
params: 
  species_code: 10110
  survey_dfinition_id: 47
  area_id: 99903
---

Synopsis for `r params$species_code`

```{r include=FALSE}
library(egg)
library(tidyverse)
library(akfingapdata)
library(akgfmaps)
library(keyring)
library(gfplot)
library(akmarineareas2)
library(sf)
library(FSA)
library(classInt)

options(scipen = 999)

  # define token for pulling gap data from akfin api
token <-create_token("akfin_secret")

source("generate_synopsis.R")

gp<-generate_synopsis(species_code=params$species_code, 
                  survey_definition_id=params$survey_dfinition_id, 
                  area_id=params$area_id,
                  start_year=1990,
                  end_year=3000)

```

```{r fig1, echo=FALSE, message=FALSE, warning=FALSE}
print(gp[1])
```

```{r fig2, echo=FALSE, message=FALSE, warning=FALSE, fig.asp=1.2}
print(gp[2])
```

```{r fig3, echo=FALSE, message=FALSE, warning=FALSE, fig.asp=1.2}
print(gp[3])
```

```{r fig4, echo=FALSE, message=FALSE, warning=FALSE}
print(gp[4])
```

```{r fig5, echo=FALSE, message=FALSE, warning=FALSE}
print(gp[5])
```

```{r fig6, echo=FALSE, message=FALSE, warning=FALSE, fig.asp=1.5}
print(gp[6])
```

```{r fig7, echo=FALSE, message=FALSE, warning=FALSE}
print(gp[7])
```
