---
format: 
  html:
    self-contained: true
editor: visual
params: 
  species_code: 30420
  survey_definition_id: 47
  area_id: 99903
---

```{r include=FALSE}
library(egg)
library(tidyverse)
library(akfingapdata)
library(akgfmaps)
library(keyring)
#library(gfplot)
library(akmarineareas2)
library(sf)
library(FSA)
library(classInt)

options(scipen = 999)

  # define token for pulling gap data from akfin api
token <-create_token("callahan_akfin_api")

source("R/get_gap_data.R")
source("R/plot_biomass.R")
source("R/plot_agecomp.R")
source("R/plot_agecomp_bubble.R")
source("R/plot_sizecomp.R")
source("R/plot_idw_last_three_years.R")
source("R/plot_length_age.R")
source("R/plot_length_weight.R")
source("R/plot_sample_size.R")

get_gap_data(species_code=params$species_code, 
                  survey_definition_id=params$survey_definition_id, 
                  area_id=params$area_id,
                  start_year=1982,
                  end_year=3000)

# region specific chunk sizing
std <- 1
tall <- 1.2
taller <- 1.5
tallest <-2.5

```

GAP Products Synopsis for `r paste(region, common_name,",", scientific_name, ",", params$species_code)`

```{r fig1, echo=FALSE, message=FALSE, warning=FALSE}
plot_biomass()
```

```{r fig2, echo=FALSE, message=FALSE, warning=FALSE, fig.asp=ifelse(params$survey_definition_id==98, tallest, tall)}
plot_sizecomp()
```

```{r fig3, echo=FALSE, message=FALSE, warning=FALSE, fig.asp=ifelse(params$survey_definition_id==98, tallest, tall)}
plot_agecomp()
```

```{r fig3.5, echo=FALSE, message=FALSE, warning=FALSE}
plot_agecomp_bubble()
```

```{r fig4, echo=FALSE, message=FALSE, warning=FALSE}
plot_length_age()
```

```{r fig5, echo=FALSE, message=FALSE, warning=FALSE}
plot_length_weight()
```

```{r include=FALSE}
idw_plot<-plot_idw_last_three_years()
```

```{r fig6, echo=FALSE, message=FALSE, warning=FALSE, fig.asp=ifelse(params$survey_definition_id==98, tallest, taller)}
idw_plot
```

```{r fig7, echo=FALSE, message=FALSE, warning=FALSE, fig.asp=ifelse(params$survey_definition_id==98, tall, std)}
plot_sample_size()
```

<https://github.com/MattCallahan-NOAA/gapproductssynopsis>
